// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollLedgerSync.Infrastructure.Persistence;

#nullable disable

namespace PayrollLedgerSync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayrollLedgerDbContext))]
    partial class PayrollLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayrollLedgerSync.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_OutboxEvents_EventType");

                    b.HasIndex("IsDeleted", "OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxEvents_SoftDelete_OccurredOn");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxEvents_ProcessingWindow");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("PayrollLedgerSync.Domain.Entities.PayrollBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayrollPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Period");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayrollPeriod")
                        .HasDatabaseName("IX_PayrollBatches_Period");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PayrollBatches_Status");

                    b.HasIndex("IsDeleted", "CreatedOnUtc")
                        .HasDatabaseName("IX_PayrollBatches_SoftDelete_CreatedOn");

                    b.ToTable("PayrollBatches", (string)null);
                });

            modelBuilder.Entity("PayrollLedgerSync.Domain.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "ProcessedOnUtc")
                        .HasDatabaseName("IX_ProcessedMessages_SoftDelete_ProcessedOn");

                    b.HasIndex("MessageFingerprint", "Consumer")
                        .IsUnique()
                        .HasDatabaseName("UX_ProcessedMessages_Fingerprint_Consumer");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("PayrollLedgerSync.Domain.Entities.PayrollBatch", b =>
                {
                    b.OwnsMany("PayrollLedgerSync.Domain.Entities.EmployeePayroll", "EmployeePayrolls", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmployeeCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("EmployeeCode");

                            b1.Property<Guid>("PayrollBatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PayrollBatchId", "EmployeeCode")
                                .HasDatabaseName("IX_EmployeePayrolls_Batch_EmployeeCode");

                            b1.ToTable("EmployeePayrolls", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PayrollBatchId");

                            b1.OwnsOne("PayrollLedgerSync.Domain.ValueObjects.Money", "Deductions", b2 =>
                                {
                                    b2.Property<Guid>("EmployeePayrollId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("DeductionAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("DeductionCurrency");

                                    b2.HasKey("EmployeePayrollId");

                                    b2.ToTable("EmployeePayrolls");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeePayrollId");
                                });

                            b1.OwnsOne("PayrollLedgerSync.Domain.ValueObjects.Money", "GrossPay", b2 =>
                                {
                                    b2.Property<Guid>("EmployeePayrollId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("GrossAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("GrossCurrency");

                                    b2.HasKey("EmployeePayrollId");

                                    b2.ToTable("EmployeePayrolls");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeePayrollId");
                                });

                            b1.OwnsOne("PayrollLedgerSync.Domain.ValueObjects.Money", "NetPay", b2 =>
                                {
                                    b2.Property<Guid>("EmployeePayrollId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("NetAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("NetCurrency");

                                    b2.HasKey("EmployeePayrollId");

                                    b2.ToTable("EmployeePayrolls");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeePayrollId");
                                });

                            b1.Navigation("Deductions")
                                .IsRequired();

                            b1.Navigation("GrossPay")
                                .IsRequired();

                            b1.Navigation("NetPay")
                                .IsRequired();
                        });

                    b.OwnsMany("PayrollLedgerSync.Domain.Entities.LedgerEntry", "LedgerEntries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid>("PayrollBatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PayrollBatchId", "AccountCode")
                                .HasDatabaseName("IX_LedgerEntries_Batch_AccountCode");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PayrollBatchId");

                            b1.OwnsOne("PayrollLedgerSync.Domain.ValueObjects.Money", "Credit", b2 =>
                                {
                                    b2.Property<Guid>("LedgerEntryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("CreditAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("CreditCurrency");

                                    b2.HasKey("LedgerEntryId");

                                    b2.ToTable("LedgerEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("LedgerEntryId");
                                });

                            b1.OwnsOne("PayrollLedgerSync.Domain.ValueObjects.Money", "Debit", b2 =>
                                {
                                    b2.Property<Guid>("LedgerEntryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("DebitAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("DebitCurrency");

                                    b2.HasKey("LedgerEntryId");

                                    b2.ToTable("LedgerEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("LedgerEntryId");
                                });

                            b1.Navigation("Credit")
                                .IsRequired();

                            b1.Navigation("Debit")
                                .IsRequired();
                        });

                    b.Navigation("EmployeePayrolls");

                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
